### ISSUE TITLE
Port more object loaders across from THREE.js

### ISSUE THREAD

**Issue by Floppy** [danini-the-panini/mittsu#116]
In my THREE.js code, as well as OBJLoader (which is already in mittsu), I use:

* STLLoader
* ThreeMFLoader
* PLYLoader

These are all currently in the ["examples" section of the THREE.js code](https://github.com/mrdoob/three.js/tree/master/examples/jsm/loaders) rather than the core, I'm not really sure why. If I port them to Ruby, would you be OK with them being in the core, or should I perhaps create a separate `mittsu-extra-loaders` gem?

**Comment by danini-the-panini** [comment]
I think it's separate from THREE.js to minimise the size of the JS, which isn't a big deal for a ruby gem, so I'm all for it being in core 👍🏻

**Comment by Floppy** [comment]
Nice one, I'll have a crack at one of them to get started, see how I get on.

**Comment by Floppy** [comment]
The 3MF loader will go into https://github.com/manyfold3d/mittsu-3mf when I get round to writing it, so I'll close this. We have STL in the core now, which is good, 3MF as an extra, and tbh PLY is only there for feature-equivalence with what I'm personally using in THREE.js, so I think it's not super important.

**Comment by Floppy** [comment]
And https://github.com/manyfold3d/mittsu-3mf of course now provides a model for extension gems to add loaders and exporters.
