### ISSUE TITLE
Render to an image?

### ISSUE THREAD

**Issue by ndbroadbent** [danini-the-panini/mittsu#75]
Hello,

Thanks for working on this awesome library! The examples have been really useful, and I've been able to hack together something that works.

Is it possible to render these scenes as an image? I couldn't find anything in the source code, and I'm not sure how to do it with OpenGL. It would be great if there was an example that rendered to an image, instead of opening the window.

This could also be quite useful for some test cases. You could render a scene to an image, and then compare the images with a perceptual hash.

**Comment by jellymann** [comment]
It's not supported directly, but is definitely something that can be implemented.

**Comment by ndbroadbent** [comment]
Thanks for the reply! I just wanted to check to see if I missed anything in `mittsu` or `glfw`. I didn't end up needing this, and I just took some screenshots and videos of the window. Feel free to close this if it would be too much work!

**Comment by danini-the-panini** [comment]
@ndbroadbent I have added a `Mittsu::OpenGL::Renderer#take_screenshot` method in the now-separated [mittsu-opengl](https://github.com/danini-the-panini/mittsu-opengl) gem
