### ISSUE TITLE
How to take a screenshot?

### ISSUE THREAD

**Issue by pascalr** [danini-the-panini/mittsu#96]
Hello I was wondering how I can get the pixel values that are rendered to the screen. I got this so far:

```
module RendererPatch
  def take_screenshot(x,y,width,height)
    pixels = []
    glReadPixels(x,y,width,height,GL_RGB,GL_FLOAT,pixels)
  end
end
Mittsu::OpenGLRenderer.include RendererPatch
```

But I don't understand what kind of variable pixels is supposed to be. It's complaining:

> /var/lib/gems/2.7.0/gems/opengl-bindings-1.6.10/lib/opengl_command.rb:246:in []: can't convert Array into Integer (TypeError)

 This is the method source code from opengl-bindings:

```
GL_FUNCTIONS_ARGS_MAP[:glReadPixels] = [Fiddle::TYPE_INT, Fiddle::TYPE_INT, Fiddle::TYPE_INT, Fiddle::TYPE_INT,
                                        -Fiddle::TYPE_INT, -Fiddle::TYPE_INT, Fiddle::TYPE_VOIDP]
GL_FUNCTIONS_RETVAL_MAP[:glReadPixels] = Fiddle::TYPE_VOID
def glReadPixels(_x_, _y_, _width_, _height_, _format_, _type_, _pixels_)
  f = OpenGL::get_command(:glReadPixels)
  f.call(_x_, _y_, _width_, _height_, _format_, _type_, _pixels_)
end
```

PS: Thanks for the great library!

**Comment by jellymann** [comment]
I think pixels should be a string of length width*height*floatSize, and then to turn it into an array of floats you would call `pixels.unpack('F*')`

I should really just add a function to do this and output a ChunkyPNG object or something.

Possibly related to #75

**Comment by pascalr** [comment]
That would be great if you manage to add a function that outputs a png!

I tried with the string, but I didn't get very far, somehow it made my application crash without any error messages.

I believe the length of the string should be multiplied by `width*height*4*3` in my case since I wanted RGB, but probably mutliplied by 4 for GL_RGBA for a png.

**Comment by jellymann** [comment]
Oh right, I forgot about the number of channels 🤦‍♀️

**Comment by pascalr** [comment]
I was finally able to do it with this:

```
module RendererPatch
  def take_screenshot(x,y,width,height)
    type_nb_bytes = 1 # for GL_UNSIGNED_BYTE (0 to 255)
    nb_channels = 3 # for GL_RGB
    pixels = ' '*width*height*type_nb_bytes*nb_channels
    glReadPixels(x,y,width,height,GL_RGB,GL_UNSIGNED_BYTE,pixels)
    png = ChunkyPNG::Image.from_rgb_stream(width, height, pixels)
    png.flip_horizontally!
    png.save('screenshot.png', :interlace => true)
  end
end
Mittsu::OpenGLRenderer.include RendererPatch
```

**Comment by danini-the-panini** [comment]
@pascalr I have incorporated your screenshot method into the now-separated [mittsu-opengl](https://github.com/danini-the-panini/mittsu-opengl) gem
